#The below values must be set correctly:
#'name', 'url', 'token' values according to the values from the docker container's "/etc/gitlab-runner/config.toml"
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |-
    concurrent = 4
    [[runners]]
      name = "java-dev-cluster"
      url = "https://gitlab.lnu.se/"
      token = "re79MbhzyLWJ-SCJNQiP"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        poll_timeout = 600
        cpu_request = "1"
        service_cpu_request = "200m"
        [[runners.kubernetes.volumes.host_path]]
            name = "docker"
            mount_path = "/var/run/docker.sock"
            host_path = "/var/run/docker.sock"


