---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-client
  template:
    metadata:
      labels:
        app: webapp-client
    spec:
      containers:
      - name: client
        image: gitlab.lnu.se:5050/ro222fd/2dv611-grp3/client:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gitlab-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp-client
  ports:
  - port: 3000
    nodePort: 31234
  type: NodePort