version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      # Anonymous volume to prevent overwrite
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_URL: http://localhost:4000 # The requests are sent from the local browser (outside Docker network)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./api:/usr/src/app
      # Anonymous volume to prevent overwrite
      - /usr/src/app/node_modules 
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password123
      URL: mariadb:3306

  mariadb:
    image: mariadb:10.2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123password
      MYSQL_DATABASE: app
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
